#! /bin/sh

# Need to either have this in your path, or make an alias for it in, like,
# zshrc. Also requires https://github.com/chriskempson/base16-shell.

function help () {
    echo "base16color-switch - Swap between the lightside and starwars. Star-wars. StarWars?"
    echo ""
    echo "    base16color-switch light - the lightness";
    echo "    base16color-switch dark  - the darkness";
}

if [ $1 ] 
then
  case "$1" in
  light)
    BASE16_SHELL="$HOME/.config/base16-shell/scripts/base16-default-light.sh"
    [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

    export BASE16_MODE=light

    if [ -n "$TMUX" ]; then
      tmux set-environment -t: BASE16_MODE light
    fi
  ;;
  dark)
    BASE16_SHELL="$HOME/.config/base16-shell/scripts/base16-default-dark.sh"
    [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

    export BASE16_MODE=dark

    if [ -n "$TMUX" ]; then
      tmux set-environment -t: BASE16_MODE dark
    fi
  ;;
  *)
    help;
  ;;
  esac
else
  help;
fi
